# Generated by Django 5.2.3 on 2025-10-20 06:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atleta',
            fields=[
                ('id_atleta', models.AutoField(primary_key=True, serialize=False)),
                ('ci_atleta', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nom_atleta', models.CharField(max_length=20)),
                ('apell_atleta', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fecha_nac', models.DateField()),
                ('altura', models.FloatField(max_length=3)),
                ('peso', models.FloatField(max_length=5)),
                ('talla', models.FloatField(max_length=3)),
                ('envergadura', models.FloatField(max_length=3)),
                ('telf_atleta', models.CharField(max_length=11)),
                ('condicion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_atletas/')),
            ],
        ),
        migrations.CreateModel(
            name='entrenador',
            fields=[
                ('ci_entrenador', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('nom_entre', models.CharField(max_length=20)),
                ('apell_entre', models.CharField(max_length=20)),
                ('telf_entre', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)])),
                ('correo_entre', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo_entre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_repre', models.CharField(max_length=15, unique=True)),
                ('nom_repre', models.CharField(max_length=20)),
                ('apell_repre', models.CharField(max_length=20)),
                ('telf_repre', models.CharField(max_length=11)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo_repre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('parentesto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asis', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_atleta', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=20, unique=True)),
                ('detalle_cat', models.TextField(blank=True, null=True)),
                ('id_atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_atleta', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='entre_asis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrenamiento', to='core.asistencia', verbose_name='Registro de Asistencia')),
                ('ci_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_supervisados', to='core.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id_hor', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('observ_hora', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_categoria', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_insc', models.DateField()),
                ('deta_insc', models.TextField(blank=True, null=True)),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_atleta', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='mensualidad',
            fields=[
                ('id_mensualidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_men', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estado_pago', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=3)),
                ('observ_men', models.TextField(blank=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_mensualidad', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.TextField(blank=True, null=True)),
                ('nom_prue', models.CharField(max_length=50)),
                ('desc_prue', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('MTS', 'Metros'), ('SEG', 'Segundos'), ('PTS', 'Puntos'), ('KIL', 'Kilogramos')], default='PTS', max_length=3)),
                ('fecha_prue', models.DateField()),
                ('observ_prue', models.TextField(blank=True, null=True)),
                ('ci_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenador_asignado', to='core.entrenador')),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_evaluado', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='insc_atle_repre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_inscrito', to='core.atleta')),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_dato', to='core.inscripcion')),
                ('ci_repre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representante_del_atleta', to='core.representante')),
            ],
        ),
        migrations.CreateModel(
            name='requisitos',
            fields=[
                ('id_req', models.AutoField(primary_key=True, serialize=False)),
                ('nom_req', models.CharField(max_length=20, unique=True)),
                ('desq_req', models.TextField(blank=True, null=True)),
                ('det_req', models.TextField(blank=True, null=True)),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_atleta', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='result_prue',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('fuerza', models.DecimalField(decimal_places=2, max_digits=3)),
                ('resistencia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_resultado', to='core.atleta')),
            ],
        ),
    ]
